package com.ylz.packcommon.webservices.serveres.impl;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * QueryServicesImplService service = new QueryServicesImplService();
 * QueryServices portType = service.getQueryServicesImplPort();
 * portType.findCheck(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "QueryServicesImplService", targetNamespace = "http://impl.serveres.webservices.packcommon.ylz.com/", wsdlLocation = "http://112.111.45.52:7001/hthquery/serfind/QueryServices?wsdl")
public class QueryServicesImplService extends Service {

	private final static URL QUERYSERVICESIMPLSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.ylz.packcommon.webservices.serveres.impl.QueryServicesImplService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ylz.packcommon.webservices.serveres.impl.QueryServicesImplService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://112.111.45.52:7001/hthquery/serfind/QueryServices?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://112.111.45.52:7001/hthquery/serfind/QueryServices?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		QUERYSERVICESIMPLSERVICE_WSDL_LOCATION = url;
	}

	public QueryServicesImplService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public QueryServicesImplService() {
		super(QUERYSERVICESIMPLSERVICE_WSDL_LOCATION, new QName(
				"http://impl.server.webservices.xmgrid.com/",
				"QueryServicesImplService"));
	}

	/**
	 * 
	 * @return returns QueryServices
	 */
	@WebEndpoint(name = "QueryServicesImplPort")
	public QueryServices getQueryServicesImplPort() {
		return super.getPort(new QName(
				"http://impl.server.webservices.xmgrid.com/",
				"QueryServicesImplPort"), QueryServices.class);
	}

}
