package com.ylz.packcommon.webservices.serveres.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "QueryServices", targetNamespace = "http://server.webservices.xmgrid.com/")
public interface QueryServices {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findCheck", targetNamespace = "http://server.webservices.xmgrid.com/", className = "com.xmgrid.webservices.server.FindCheck")
	@ResponseWrapper(localName = "findCheckResponse", targetNamespace = "http://server.webservices.xmgrid.com/", className = "com.xmgrid.webservices.server.FindCheckResponse")
	public String findCheck(
            @WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findChecks", targetNamespace = "http://server.webservices.xmgrid.com/", className = "com.xmgrid.webservices.server.FindChecks")
	@ResponseWrapper(localName = "findChecksResponse", targetNamespace = "http://server.webservices.xmgrid.com/", className = "com.xmgrid.webservices.server.FindChecksResponse")
	public String findChecks(
            @WebParam(name = "arg0", targetNamespace = "") String arg0,
            @WebParam(name = "arg1", targetNamespace = "") String arg1);

}
